### ISSUE TITLE
List in the English Wikipedia article

### ISSUE THREAD

**Issue by rwmpelstilzchen** [thiskurt/wordle-languages#1]
Hi,

I created a list of Wordle equivalents in the English Wikipedia article about Wordle ([here](https://en.wikipedia.org/wiki/Wordle_(video_game)#Equivalents_in_other_languages)). There are some languages not found on your list, so you might want to add them here :-)

Júda

**Comment by thiskurt** [comment]
Hey,

Thanks, I'll add them. I didn't find that list when I was looking for an overview.

**Comment by rwmpelstilzchen** [comment]
> Thanks, I'll add them.

Thank you for creating your list. I used it when compiling the list on Wikipedia.

> I didn't find that list when I was looking for an overview.

Yeah, that’s because I have created this section today… ^_^
