### ISSUE TITLE
Wordles of the World

### ISSUE THREAD

**Issue by rwmpelstilzchen** [thiskurt/wordle-languages#7]
Hi Kurt,

I compiled a list of Wordles. It covers the ones from your list (with due credit, of course) and some additional ones.
https://rwmpelstilzchen.gitlab.io/wordles/

Júda

**Comment by thiskurt** [comment]
Good job, I'm going to link through to that one instead.

**Comment by rwmpelstilzchen** [comment]
Thanks :-)

**Comment by thiskurt** [comment]
FYI I don't think you have one of these two Hungarian version in this issue:

https://github.com/thiskurt/wordle-languages/issues/9

And also not the Breton version in this issue:

https://github.com/thiskurt/wordle-languages/issues/8

**Comment by rwmpelstilzchen** [comment]
Thank you! ^_^

So we still need Cornish and Manx in order to have a full Celtic set…

**Comment by rwmpelstilzchen** [comment]
Now only Manx is missing…

**Comment by samanvp** [comment]
Hi @rwmpelstilzchen ,
I have been working on a [universal solver](https://github.com/samanvp/wordle-solver) that given a corpus of any language can assist users to solve the puzzle. So far I have tested it for 4 languages.

I am not sure if this is something you'd like to link from your list.

Best,

**Comment by rwmpelstilzchen** [comment]
Hi @samanvp,

Thanks for that! I added it to the [tools and miscellanea table](https://rwmpelstilzchen.gitlab.io/wordles/#misc).

With regards to optimally solving Wordle, maybe these links would be of interest to you:

* https://youtu.be/v68zYyaEmEA
* https://aperiodical.com/2022/02/a-mathematicians-guide-to-wordle/
